
name: Deploy to VPS
on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: 
      name: production
      url: https://dtrpg.online/
    steps:
      - name: Deploy to VPS
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: 22
          script: |
            {
              cd dev/DTrpg || exit 1
              eval $(ssh-agent -s)
              echo "${{ secrets.GH_DEPLOY_KEY }}" | ssh-add - || exit 1
              git pull origin master || exit 1
              
              # Setup Convex deploy key
              echo "CONVEX_DEPLOY_KEY=${{ secrets.CONVEX_DEPLOY_KEY }}" > .env.local || exit 1

              # Install dependencies
              pnpm install --frozen-lockfile || exit 1
              
              # Deploy to Convex
              pnpm convex deploy -y || exit 1
              
              # Run build and store exit code
              pnpm run build
              BUILD_EXIT_CODE=$?
              
              if [ $BUILD_EXIT_CODE -eq 0 ]; then
                echo "Build successful, reloading PM2..."
                pm2 reload dtrpg || exit 1
              else
                echo "Build failed, skipping PM2 reload"
                exit 1
              fi
            } || {
              echo "Deployment failed"
              exit 1
            }
